// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;

namespace Model.Migrations
{
    [DbContext(typeof(AsusContext))]
    [Migration("20220515223959_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Domain.Drzava", b =>
                {
                    b.Property<int>("DrzavaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivDrzave")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DrzavaId");

                    b.ToTable("Drzava");
                });

            modelBuilder.Entity("Model.Domain.Kupac", b =>
                {
                    b.Property<int>("PIB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DrzavaId")
                        .HasColumnType("int");

                    b.Property<int>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("NazivKupca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UlicaIBroj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PIB");

                    b.ToTable("Kupac");
                });

            modelBuilder.Entity("Model.Domain.OdgovornoLice", b =>
                {
                    b.Property<int>("SifraRadnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImePrezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SifraTrzista")
                        .HasColumnType("int");

                    b.HasKey("SifraRadnika");

                    b.HasIndex("SifraTrzista");

                    b.ToTable("OdgovornoLice");
                });

            modelBuilder.Entity("Model.Domain.Proizvod", b =>
                {
                    b.Property<int>("ProizvodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivModela")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProizvodId");

                    b.ToTable("Proizvod");
                });

            modelBuilder.Entity("Model.Domain.Trziste", b =>
                {
                    b.Property<int>("SifraTrzista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivTrzista")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SifraTrzista");

                    b.ToTable("Trziste");
                });

            modelBuilder.Entity("Model.Domain.Drzava", b =>
                {
                    b.OwnsMany("Model.Domain.Grad", "Gradovi", b1 =>
                        {
                            b1.Property<int>("DrzavaId")
                                .HasColumnType("int");

                            b1.Property<int>("GradId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("PostanskiBroj")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("NazivGrada")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DrzavaId", "GradId");

                            b1.ToTable("Grad");

                            b1.WithOwner("Drzava")
                                .HasForeignKey("DrzavaId");

                            b1.Navigation("Drzava");
                        });

                    b.Navigation("Gradovi");
                });

            modelBuilder.Entity("Model.Domain.OdgovornoLice", b =>
                {
                    b.HasOne("Model.Domain.Trziste", "Trziste")
                        .WithMany()
                        .HasForeignKey("SifraTrzista")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Trziste");
                });

            modelBuilder.Entity("Model.Domain.Proizvod", b =>
                {
                    b.OwnsMany("Model.Domain.Karakteristika", "Karakteristike", b1 =>
                        {
                            b1.Property<int>("ProizvodId")
                                .HasColumnType("int");

                            b1.Property<int>("KarakteristikaId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("NazivKarakteristike")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Vrednost")
                                .HasColumnType("float");

                            b1.HasKey("ProizvodId", "KarakteristikaId");

                            b1.ToTable("Karakteristika");

                            b1.WithOwner("Proizvod")
                                .HasForeignKey("ProizvodId");

                            b1.Navigation("Proizvod");
                        });

                    b.Navigation("Karakteristike");
                });
#pragma warning restore 612, 618
        }
    }
}
